#ifndef COLOR_HPP
#define COLOR_HPP

#define ALICEBLUE                   0xF0F8FFFF
#define ANTIQUEWHITE                0xFAEBD7FF
#define AQUA                        0x00FFFFFF
#define AQUAMARINE                  0x7FFFD4FF
#define AZURE                       0xF0FFFFFF
#define BEIGE                       0xF5F5DCFF
#define BISQUE                      0xFFE4C4FF
#define BLACK                       0x000000FF
#define BLANCHEDALMOND              0xFFEBCDFF
#define BLUE                        0x0000FFFF
#define BLUEVIOLET                  0x8A2BE2FF
#define BROWN                       0xA52A2AFF
#define BURLYWOOD                   0xDEB887FF
#define CADETBLUE                   0x5F9EA0FF
#define CHARTREUSE                  0x7FFF00FF
#define CHOCOLATE                   0xD2691EFF
#define CORAL                       0xFF7F50FF
#define CORNFLOWERBLUE              0x6495EDFF
#define CORNSILK                    0xFFF8DCFF
#define CRIMSON                     0xDC143CFF
#define CYAN                        0x00FFFFFF
#define DARKBLUE                    0x00008BFF
#define DARKCYAN                    0x008B8BFF
#define DARKGOLDENROD               0xB8860BFF
#define DARKGRAY                    0xA9A9A9FF
#define DARKGREEN                   0x006400FF
#define DARKKHAKI                   0xBDB76BFF
#define DARKMAGENTA                 0x8B008BFF
#define DARKOLIVEGREEN              0x556B2FFF
#define DARKORANGE                  0xFF8C00FF
#define DARKORCHID                  0x9932CCFF
#define DARKRED                     0x8B0000FF
#define DARKSALMON                  0xE9967AFF
#define DARKSEAGREEN                0x8FBC8FFF
#define DARKSLATEBLUE               0x483D8BFF
#define DARKSLATEGRAY               0x2F4F4FFF
#define DARKTURQUOISE               0x00CED1FF
#define DARKVIOLET                  0x9400D3FF
#define DEEPPINK                    0xFF1493FF
#define DEEPSKYBLUE                 0x00BFFFFF
#define DIMGRAY                     0x696969FF
#define DODGERBLUE                  0x1E90FFFF
#define FIREBRICK                   0xB22222FF
#define FLORALWHITE                 0xFFFAF0FF
#define FORESTGREEN                 0x228B22FF
#define FUCHSIA                     0xFF00FFFF
#define GAINSBORO                   0xDCDCDCFF
#define GHOSTWHITE                  0xF8F8FFFF
#define GOLD                        0xFFD700FF
#define GOLDENROD                   0xDAA520FF
#define GRAY                        0x808080FF
#define GREEN                       0x008000FF
#define GREENYELLOW                 0xADFF2FFF
#define HONEYDEW                    0xF0FFF0FF
#define HOTPINK                     0xFF69B4FF
#define INDIANRED                   0xCD5C5CFF
#define INDIGO                      0x4B0082FF
#define IVORY                       0xFFFFF0FF
#define KHAKI                       0xF0E68CFF
#define LAVENDER                    0xE6E6FAFF
#define LAVENDERBLUSH               0xFFF0F5FF
#define LAWNGREEN                   0x7CFC00FF
#define LEMONCHIFFON                0xFFFACDFF
#define LIGHTBLUE                   0xADD8E6FF
#define LIGHTCORAL                  0xF08080FF
#define LIGHTCYAN                   0xE0FFFFFF
#define LIGHTGOLDENRODYELlow        0xFAFAD2FF
#define LIGHTGRAY                   0xD3D3D3FF
#define LIGHTGREEN                  0x90EE90FF
#define LIGHTPINK                   0xFFB6C1FF
#define LIGHTSALMON                 0xFFA07AFF
#define LIGHTSEAGREEN               0x20B2AAFF
#define LIGHTSKYBLUE                0x87CEFAFF
#define LIGHTSLATEGRAY              0x778899FF
#define LIGHTSTEELBLUE              0xB0C4DEFF
#define LIGHTYELLOW                 0xFFFFE0FF
#define LIME                        0x00FF00FF
#define LIMEGREEN                   0x32CD32FF
#define LINEN                       0xFAF0E6FF
#define MAGENTA                     0xFF00FFFF
#define MAROON                      0x800000FF
#define MEDIUMAQUAMARINE            0x66CDAAFF
#define MEDIUMBLUE                  0x0000CDFF
#define MEDIUMORCHID                0xBA55D3FF
#define MEDIUMPURPLE                0x9370DBFF
#define MEDIUMSEAGREEN              0x3CB371FF
#define MEDIUMSLATEBLUE             0x7B68EEFF
#define MEDIUMSPRINGGREEN           0x00FA9AFF
#define MEDIUMTURQUOISE             0x48D1CCFF
#define MEDIUMVIOLETRED             0xC71585FF
#define MIDNIGHTBLUE                0x191970FF
#define MINTCREAM                   0xF5FFFAFF
#define MISTYROSE                   0xFFE4E1FF
#define MOCCASIN                    0xFFE4B5FF
#define NAVAJOWHITE                 0xFFDEADFF
#define NAVY                        0x000080FF
#define OLDLACE                     0xFDF5E6FF
#define OLIVE                       0x808000FF
#define OLIVEDRAB                   0x6B8E23FF
#define ORANGE                      0xFFA500FF
#define ORANGERED                   0xFF4500FF
#define ORCHID                      0xDA70D6FF
#define PALEGOLDENROD               0xEEE8AAFF
#define PALEGREEN                   0x98FB98FF
#define PALETURQUOISE               0xAFEEEEFF
#define PALEVIOLETRED               0xDB7093FF
#define PAPAYAWHIP                  0xFFEFD5FF
#define PEACHPUFF                   0xFFDAB9FF
#define PERU                        0xCD853FFF
#define PINK                        0xFFC0CBFF
#define PLUM                        0xDDA0DDFF
#define POWDERBLUE                  0xB0E0E6FF
#define PURPLE                      0x800080FF
#define REBECCAPURPLE               0x663399FF
#define RED                         0xFF0000FF
#define ROSYBROWN                   0xBC8F8FFF
#define ROYALBLUE                   0x4169E1FF
#define SADDLEBROWN                 0x8B4513FF
#define SALMON                      0xFA8072FF
#define SANDYBROWN                  0xF4A460FF
#define SEAGREEN                    0x2E8B57FF
#define SEASHELL                    0xFFF5EEFF
#define SIENNA                      0xA0522DFF
#define SILVER                      0xC0C0C0FF
#define SKYBLUE                     0x87CEEBFF
#define SLATEBLUE                   0x6A5ACDFF
#define SLATEGRAY                   0x708090FF
#define SNOW                        0xFFFAFAFF
#define SPRINGGREEN                 0x00FF7FFF
#define STEELBLUE                   0x4682B4FF
#define TAN                         0xD2B48CFF
#define TEAL                        0x008080FF
#define THISTLE                     0xD8BFD8FF
#define TOMATO                      0xFF6347FF
#define TURQUOISE                   0x40E0D0FF
#define VIOLET                      0xEE82EEFF
#define WHEAT                       0xF5DEB3FF
#define WHITE                       0xFFFFFFFF
#define WHITESMOKE                  0xF5F5F5FF
#define YELLOW                      0xFFFF00FF
#define YELLOWGREEN                 0x9ACD32FF

#endif